name: Deploy Angular UTEQ

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # ESTE PASO NOS DIRÁ LA VERDAD: ¿Dónde están los archivos?
      - name: List files for debugging
        run: ls -R

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          # Intentamos construir buscando el archivo en todo el repositorio
          DOCKERFILE_PATH=$(find . -name "Dockerfile" | head -n 1)
          echo "Dockerfile encontrado en: $DOCKERFILE_PATH"
          docker build -t ${{ secrets.DOCKER_USER }}/remedial-front:latest -f "$DOCKERFILE_PATH" .
          docker push ${{ secrets.DOCKER_USER }}/remedial-front:latest

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: riveradiazjanine
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker stop app-frontend || true
            docker rm app-frontend || true
            docker pull ${{ secrets.DOCKER_USER }}/remedial-front:latest
            docker run -d --name app-frontend -p 3001:80 ${{ secrets.DOCKER_USER }}/remedial-front:latest
